import { z } from 'zod';

import {
  FamilyIdSchema,
  LatitudeSchema,
  LongitudeSchema,
  UserIdSchema,
  type LocationEvent,
} from '@family/contracts';

/**
 * Wire/at-rest format for an encrypted coordinate pair (spec §20).
 *
 * Coordinates never touch persistent storage in plaintext. A per-family (or
 * per-family-and-user) data key generated by KMS wraps the AES-256-GCM
 * ciphertext; only the wrapped key is persisted alongside the record.
 */

/** Name recorded on every record so a future algorithm change is detectable. */
export const COORDINATE_ENCRYPTION_ALGORITHM = 'AES-256-GCM' as const;

/** node:crypto identifier for {@link COORDINATE_ENCRYPTION_ALGORITHM}. */
export const NODE_CIPHER_ALGORITHM = 'aes-256-gcm' as const;

/** Current plaintext payload layout version. */
export const COORDINATE_SCHEMA_VERSION = 1;

/** Layouts this build is able to decrypt. */
export const SUPPORTED_COORDINATE_SCHEMA_VERSIONS: readonly number[] = [1];

/** AES-GCM parameters. 96-bit IVs and 128-bit tags are the NIST-recommended pair. */
export const IV_BYTES = 12;
export const AUTH_TAG_BYTES = 16;
export const DATA_KEY_BYTES = 32;

/** Two IEEE-754 doubles, little-endian: [latitude, longitude]. */
export const COORDINATE_PAYLOAD_BYTES = 16;

export const CoordinatesSchema = z.object({
  lat: LatitudeSchema,
  lng: LongitudeSchema,
});
export type Coordinates = z.infer<typeof CoordinatesSchema>;

/**
 * Identifies which data key protects a record and, critically, binds the
 * ciphertext to a single family/user. A record encrypted for family A can never
 * be decrypted while claiming family B.
 */
export const KeyContextSchema = z.object({
  familyId: FamilyIdSchema,
  /**
   * Optional narrower binding. Present when a record belongs to one member's
   * location stream rather than to the family as a whole; when present it is
   * part of the KMS encryption context and the GCM additional authenticated
   * data, so it cannot be swapped after the fact.
   */
  userId: UserIdSchema.optional(),
});
export type KeyContext = z.infer<typeof KeyContextSchema>;

export const EncryptedCoordinateRecordSchema = z.object({
  /** base64, AES-256-GCM ciphertext of the 16-byte coordinate payload. */
  ciphertext: z.string().min(1),
  /** base64, 12 random bytes, unique per record. */
  iv: z.string().min(1),
  /** base64, 16-byte GCM authentication tag. */
  authTag: z.string().min(1),
  /** base64, the KMS-wrapped data key. Safe to persist. */
  encryptedDataKey: z.string().min(1),
  /** KMS key id/ARN that wrapped the data key, for rotation and audit. */
  keyId: z.string().min(1),
  algorithm: z.literal(COORDINATE_ENCRYPTION_ALGORITHM),
  schemaVersion: z.number().int().positive(),
});
export type EncryptedCoordinateRecord = z.infer<typeof EncryptedCoordinateRecordSchema>;

/**
 * Narrowing helper for ingestion: pulls the coordinate pair out of a validated
 * {@link LocationEvent} so callers never hand-roll the field mapping.
 */
export function coordinatesFromLocationEvent(
  event: Pick<LocationEvent, 'latitude' | 'longitude'>,
): Coordinates {
  return { lat: event.latitude, lng: event.longitude };
}
